.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "I2PBROWSER" "1" "January 2020" "tb-starter" "tb-starter Manual"
.SH "NAME"
\fBi2pbrowser\fR \- i2p Browser Update and Start Script
.SH "SYNOPSIS"
\fBi2pbrowser\fR option(s)
.SH "DESCRIPTION"
You can use \fBi2pbrowser\fR to start i2p Browser from the command line\. In Whonix, i2p browser is a separate, modified Tor Browser for use with i2p\.
.P
Parameters are passed to i2p Browser\.
.SH "CONFIG FILE"
/etc/i2pbrowser\.d/30_default\.conf
.SH "EXIT CODES"
0 Success
.P
1 Error
.SH "EXAMPLES"
\fBi2pbrowser \-\-new\-tab https://www\.i2p\-projekt\.i2p\fR
.P
\fBi2pbrowser \-\-new\-window https://www\.i2p\-projekt\.i2p\fR
.P
\fBi2pbrowser \-\-start \-\-lang="ar"\fR
.SH "NOTES"
Do not run as root!
.SH "PORTING"
This script is currently only tested in Whonix\. It could be easily made to work in Tails or on any Linux\.
.SH "WWW"
https://www\.whonix\.org/wiki/Tor_Browser
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
