.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "TORBROWSER" "1" "January 2020" "tb-starter" "tb-starter Manual"
.SH "NAME"
\fBtorbrowser\fR \- Tor Browser Update and Start Script
.SH "SYNOPSIS"
\fBtorbrowser\fR option(s)
.SH "DESCRIPTION"
You can use \fBtorbrowser\fR to start Tor Browser from the command line\.
.P
Parameters are passed to Tor Browser\.
.SH "OPTIONS"
.IP "\[ci]" 4
tb_no_start
.IP "" 0
.P
If set to "true", don't start torbrowser, exit with error code\.
.SH "FILES"
/etc/torbrowser\.d/*\.conf
.P
/usr/local/etc/torbrowser\.d/*\.conf
.SH "EXIT CODES"
0 Success
.P
1 Error
.SH "EXAMPLES"
\fBtorbrowser \-\-new\-tab https://www\.whonix\.org\fR
.P
\fBtorbrowser \-\-new\-window https://www\.whonix\.org\fR
.P
\fBtorbrowser \-\-start \-\-lang="ar"\fR
.SH "NOTES"
Do not run as root!
.SH "PORTING"
This script is currently only tested in Whonix\. It could be easily made to work in Tails or on any Linux\.
.SH "WWW"
https://www\.whonix\.org/wiki/Tor_Browser
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
