#!/bin/bash

## Copyright (C) 2020 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## https://forums.whonix.org/t/installation-and-fix-of-i2p-inside-whonix-workstation-by-default/8610

set -x
set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose

/bin/systemctl --no-pager --no-block status privoxy.service i2p.service

exit "$?"
